import React from 'react'
import Header from '../components/Header'

const PrivacyPolicy = () => {
  return (
    <div className="min-h-screen bg-white py-16 px-4 sm:px-6 lg:px-8">
      <Header />
      <div className="max-w-4xl mt-10 xl:mt-24 mx-auto">
        <h1 className="text-3xl font-bold text-gray-900 mb-8">Privacy Policy</h1>
        <p className="text-sm text-gray-500 mb-8">Last updated: April 2, 2025</p>
        
        <div className="space-y-8 text-gray-600">
          <div className="space-y-4">
            <p>
              This Privacy Policy describes Our policies and procedures on the collection, use, and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.
            </p>
            <p>
              We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy.
            </p>
          </div>

          <div className="space-y-4">
            <h2 className="text-2xl font-semibold text-gray-800">Interpretation and Definitions</h2>
            <div className="space-y-2">
              <h3 className="text-xl font-medium text-gray-700">Interpretation</h3>
              <p>
                The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or plural.
              </p>

              <h3 className="text-xl font-medium text-gray-700">Definitions</h3>
              <p>For the purposes of this Privacy Policy:</p>
              <ul className="list-disc pl-6 space-y-2">
                <li><span className="font-medium">Account</span> means a unique account created for You to access our Service or parts of our Service.</li>
                <li><span className="font-medium">Company</span> (referred to as either &ldquo;the Company&rdquo;, &ldquo;We&rdquo;, &ldquo;Us&rdquo; or &ldquo;Our&rdquo; in this Agreement) refers to Carfilio LLC, 320 Northern Blvd Suite 21, Great Neck, NY 11021.</li>
                <li><span className="font-medium">Cookies</span> are small files that are placed on Your computer, mobile device, or any other device by a website, containing the details of Your browsing history on that website among its many uses.</li>
                <li><span className="font-medium">Country</span> refers to: New York, United States</li>
                <li><span className="font-medium">Device</span> means any device that can access the Service such as a computer, a cellphone, or a digital tablet.</li>
                <li><span className="font-medium">Personal Data</span> is any information that relates to an identified or identifiable individual.</li>
                <li><span className="font-medium">Service</span> refers to the Website.</li>
                <li><span className="font-medium">Service Provider</span> means any natural or legal person who processes the data on behalf of the Company.</li>
                <li><span className="font-medium">Usage Data</span> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself.</li>
                <li><span className="font-medium">Website</span> refers to Carfilio, accessible from https://carfilio.com</li>
                <li><span className="font-medium">You</span> means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.</li>
              </ul>
            </div>
          </div>

          <div className="space-y-4">
            <h2 className="text-2xl font-semibold text-gray-800">Collecting and Using Your Personal Data</h2>
            <div className="space-y-2">
              <h3 className="text-xl font-medium text-gray-700">Types of Data Collected</h3>
              
              <h4 className="text-lg font-medium text-gray-700">Personal Data</h4>
              <p>While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:</p>
              <ul className="list-disc pl-6 space-y-1">
                <li>Email address</li>
                <li>First name and last name</li>
                <li>Phone number</li>
              </ul>

              <h4 className="text-lg font-medium text-gray-700">Usage Data</h4>
              <p>Usage Data is collected automatically when using the Service.</p>
              <p>Usage Data may include information such as Your Device&apos;s Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data.</p>
              <p>When You access the Service by or through a mobile device, We may collect certain information automatically, including, but not limited to, the type of mobile device You use, Your mobile device unique ID, the IP address of Your mobile device, Your mobile operating system, the type of mobile Internet browser You use, unique device identifiers and other diagnostic data.</p>
              <p>We may also collect information that Your browser sends whenever You visit our Service or when You access the Service by or through a mobile device.</p>
            </div>
          </div>

          <div className="space-y-4">
            <h2 className="text-2xl font-semibold text-gray-800">Tracking Technologies and Cookies</h2>
            <div className="space-y-2">
              <p>We use Cookies and similar tracking technologies to track the activity on Our Service and store certain information. Tracking technologies used are beacons, tags, and scripts to collect and track information and to improve and analyze Our Service.</p>
              
              <h3 className="text-xl font-medium text-gray-700">Types of Cookies We Use</h3>
              <ul className="list-disc pl-6 space-y-2">
                <li><span className="font-medium">Cookies or Browser Cookies.</span> A cookie is a small file placed on Your Device. You can instruct Your browser to refuse all Cookies or to indicate when a Cookie is being sent. However, if You do not accept Cookies, You may not be able to use some parts of our Service.</li>
                <li><span className="font-medium">Web Beacons.</span> Certain sections of our Service and our emails may contain small electronic files known as web beacons that permit the Company to count users who have visited those pages or opened an email.</li>
              </ul>

              <h3 className="text-xl font-medium text-gray-700">Use of Cookies</h3>
              <p>We use both Session and Persistent Cookies for the following purposes:</p>
              <ul className="list-disc pl-6 space-y-2">
                <li><span className="font-medium">Necessary / Essential Cookies</span>
                  <ul className="list-disc pl-6 mt-1">
                    <li>Type: Session Cookies</li>
                    <li>Administered by: Us</li>
                    <li>Purpose: These Cookies are essential to provide You with services available through the Website.</li>
                  </ul>
                </li>
                <li><span className="font-medium">Cookies Policy / Notice Acceptance Cookies</span>
                  <ul className="list-disc pl-6 mt-1">
                    <li>Type: Persistent Cookies</li>
                    <li>Administered by: Us</li>
                    <li>Purpose: These Cookies identify if users have accepted the use of cookies on the Website.</li>
                  </ul>
                </li>
                <li><span className="font-medium">Functionality Cookies</span>
                  <ul className="list-disc pl-6 mt-1">
                    <li>Type: Persistent Cookies</li>
                    <li>Administered by: Us</li>
                    <li>Purpose: These Cookies allow us to remember choices You make when You use the Website.</li>
                  </ul>
                </li>
              </ul>
            </div>
          </div>

          <div className="space-y-4">
            <h2 className="text-2xl font-semibold text-gray-800">Use of Your Personal Data</h2>
            <div className="space-y-2">
              <p>The Company may use Personal Data for the following purposes:</p>
              <ul className="list-disc pl-6 space-y-2">
                <li>To provide and maintain our Service, including to monitor the usage of our Service.</li>
                <li>To manage Your Account: to manage Your registration as a user of the Service.</li>
                <li>For the performance of a contract: the development, compliance, and undertaking of the purchase contract for the products, items or services You have purchased.</li>
                <li>To contact You: To contact You by email, telephone calls, SMS, or other equivalent forms of electronic communication.</li>
                <li>To provide You with news, special offers and general information about other goods, services, and events.</li>
                <li>To manage Your requests: To attend and manage Your requests to Us.</li>
                <li>For business transfers: We may use Your information to evaluate or conduct a merger, divestiture, restructuring, reorganization, dissolution, or other sale or transfer.</li>
                <li>For other purposes: We may use Your information for other purposes, such as data analysis, identifying usage trends, determining the effectiveness of our promotional campaigns.</li>
              </ul>

              <h3 className="text-xl font-medium text-gray-700">Sharing Your Personal Information</h3>
              <p>We may share Your personal information in the following situations:</p>
              <ul className="list-disc pl-6 space-y-2">
                <li>With Service Providers: We may share Your personal information with Service Providers to monitor and analyze the use of our Service.</li>
                <li>For business transfers: We may share or transfer Your personal information in connection with, or during negotiations of, any merger, sale of Company assets, financing, or acquisition.</li>
                <li>With Affiliates: We may share Your information with Our affiliates, in which case we will require those affiliates to honor this Privacy Policy.</li>
                <li>With business partners: We may share Your information with Our business partners to offer You certain products, services, or promotions.</li>
                <li>With other users: when You share personal information or otherwise interact in the public areas with other users.</li>
                <li>With Your consent: We may disclose Your personal information for any other purpose with Your consent.</li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}

export default PrivacyPolicy 